version: '1'

services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: example2394283741298379218374
      POSTGRES_USER: getroller
      POSTGRES_DB: test
    volumes:
      - /volumes
    ports:
      - ${POSTGRES_PORT:-5432}:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  C: